2019-03-01 19:09:00,295 [8999] INFO     __main__: only to rotating file logger
2019-03-01 19:09:00,295 [8999] ERROR    __main__: both log files, including errors only
2019-03-01 19:11:14,150 [9162] INFO     __main__: only to rotating file logger
2019-03-01 19:11:14,151 [9162] ERROR    __main__: both log files, including errors only
2019-03-01 19:29:46,742 [10337] INFO     __main__: only to rotating file logger
2019-03-01 19:29:46,743 [10337] ERROR    __main__: both log files, including errors only
2019-03-01 19:29:46,743 [10337] CRITICAL root: Traceback (most recent call last):
  File "log_with_daiquiri.py", line 25, in <module>
    logger.debug('This vector is bad', vec=vec)
  File "/usr/lib/python3.6/logging/__init__.py", line 1296, in debug
    self._log(DEBUG, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'vec'

2019-03-01 19:29:52,054 [10355] INFO     __main__: only to rotating file logger
2019-03-01 19:29:52,054 [10355] ERROR    __main__: both log files, including errors only
2019-03-01 19:29:52,054 [10355] CRITICAL root: Traceback (most recent call last):
  File "log_with_daiquiri.py", line 25, in <module>
    logger.debug('This vector is bad', vec=vec)
  File "/usr/lib/python3.6/logging/__init__.py", line 1296, in debug
    self._log(DEBUG, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'vec'

2019-03-01 19:31:59,132 [10642] INFO     __main__: only to rotating file logger
2019-03-01 19:31:59,132 [10642] ERROR    __main__: both log files, including errors only
2019-03-01 19:31:59,133 [10642] CRITICAL root: Traceback (most recent call last):
  File "log_with_daiquiri.py", line 25, in <module>
    logger.debug('This vector is bad', vec=str(vec))
  File "/usr/lib/python3.6/logging/__init__.py", line 1296, in debug
    self._log(DEBUG, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'vec'

2019-03-01 19:33:18,676 [10780] INFO     __main__: only to rotating file logger
2019-03-01 19:33:18,676 [10780] ERROR    __main__: both log files, including errors only
2019-03-01 19:33:18,676 [10780] CRITICAL root: Traceback (most recent call last):
  File "log_with_daiquiri.py", line 25, in <module>
    logger.debug('This vector is bad', vec=svec)
NameError: name 'svec' is not defined

2019-03-01 19:34:16,594 [10857] INFO     __main__: only to rotating file logger
2019-03-01 19:34:16,594 [10857] ERROR    __main__: both log files, including errors only
2019-03-01 19:34:16,594 [10857] CRITICAL root: Traceback (most recent call last):
  File "log_with_daiquiri.py", line 25, in <module>
    logger.debug('This vector is bad', vec=svec)
NameError: name 'svec' is not defined

2019-03-01 19:34:36,232 [10911] INFO     __main__: only to rotating file logger
2019-03-01 19:34:36,233 [10911] ERROR    __main__: both log files, including errors only
2019-03-01 19:34:36,233 [10911] DEBUG    __main__ [vec: {'toto': 7}]: This vector is bad
2019-03-01 19:36:03,041 [11001] INFO     __main__: only to rotating file logger
2019-03-01 19:36:03,041 [11001] ERROR    __main__: both log files, including errors only
2019-03-01 19:36:03,041 [11001] DEBUG    __main__ [vec: {'toto': 7}]: This vector is bad
2019-03-01 19:36:03,041 [11001] CRITICAL root: Traceback (most recent call last):
  File "log_with_daiquiri.py", line 32, in <module>
    logger = logger.getLogger(__name__)
AttributeError: 'KeywordArgumentAdapter' object has no attribute 'getLogger'

2019-03-01 19:36:26,885 [11044] INFO     __main__: only to rotating file logger
2019-03-01 19:36:26,885 [11044] ERROR    __main__: both log files, including errors only
2019-03-01 19:36:26,885 [11044] DEBUG    __main__ [vec: {'toto': 7}]: This vector is bad
2019-03-01 19:36:26,885 [11044] INFO     __main__: only to rotating file logger
2019-03-01 19:36:26,885 [11044] ERROR    __main__: both log files, including errors only
2019-03-01 19:36:26,886 [11044] DEBUG    __main__: This vector is bad {'toto': 7}
2019-03-01 19:36:42,460 [11072] INFO     __main__: only to rotating file logger
2019-03-01 19:36:42,460 [11072] ERROR    __main__: both log files, including errors only
2019-03-01 19:36:42,460 [11072] DEBUG    __main__ [vec: [1 2 3]]: This vector is bad
2019-03-01 19:36:42,461 [11072] INFO     __main__: only to rotating file logger
2019-03-01 19:36:42,461 [11072] ERROR    __main__: both log files, including errors only
2019-03-01 19:36:42,461 [11072] DEBUG    __main__: This vector is bad [1 2 3]
